osx_image: xcode12.2
language: objective-c
xcode_destination: platform=iOS Simulator,OS=14.2,name=iPhone 12 mini

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/GLTFMac.xcworkspace -scheme GLTFMac-Example -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 12 mini' -sdk iphonesimulator14.2 ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint --allow-warnings
